# Generated by Django 2.2.3 on 2020-11-12 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=64, null=True, verbose_name='资产名称')),
                ('asset_model', models.CharField(blank=True, max_length=32, verbose_name='型号')),
                ('specification', models.CharField(blank=True, max_length=256, verbose_name='规格参数')),
                ('department', models.CharField(blank=True, max_length=16, verbose_name='所属部门')),
                ('purchase_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='采购时间')),
                ('used_time', models.CharField(blank=True, max_length=64, verbose_name='使用年限')),
                ('asset_uuid', models.CharField(blank=True, max_length=128, unique=True, verbose_name='唯一标示')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.CreateModel(
            name='ServerHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.IntegerField(verbose_name='资产ID')),
                ('asset_name', models.CharField(max_length=64, null=True, verbose_name='资产名称')),
                ('asset_model', models.CharField(blank=True, max_length=32, verbose_name='型号')),
                ('specification', models.CharField(max_length=256, verbose_name='规格参数')),
                ('asset_holder', models.CharField(max_length=32, verbose_name='持有人')),
                ('department', models.CharField(max_length=16, verbose_name='所属部门')),
                ('purchase_time', models.CharField(max_length=64, verbose_name='采购时间')),
                ('used_time', models.CharField(max_length=64, verbose_name='使用年限')),
                ('asset_uuid', models.CharField(max_length=128, verbose_name='唯一标示')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产历史表',
                'verbose_name_plural': '资产历史表',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=16, verbose_name='资产类型')),
            ],
            options={
                'verbose_name': '资产类型表',
                'verbose_name_plural': '资产类型表',
            },
        ),
    ]
