# Generated by Django 2.2.3 on 2020-11-14 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20201112_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='采购时间'),
        ),
        migrations.AlterField(
            model_name='assethis',
            name='purchase_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='采购时间'),
        ),
    ]
