# Generated by Django 2.2.3 on 2020-11-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20201116_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_dep', to='users.Department', verbose_name='所属部门'),
        ),
    ]
