# Generated by Django 2.2.3 on 2020-11-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201116_2158'),
        ('asset', '0007_auto_20201116_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='department',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Department'),
        ),
    ]
