# Generated by Django 2.2.3 on 2020-11-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20201116_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
