# Generated by Django 2.2.3 on 2020-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20201119_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethis',
            name='specification',
            field=models.TextField(blank=True, verbose_name='规格参数'),
        ),
    ]
