# Generated by Django 2.2.3 on 2020-11-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20201121_1341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='Asset',
        ),
        migrations.AlterModelTable(
            name='assetstatus',
            table='AssetStatus',
        ),
        migrations.AlterModelTable(
            name='assettype',
            table='AssetType',
        ),
    ]
