# Generated by Django 2.2.3 on 2020-12-24 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20201121_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(blank=True, max_length=8, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=64, null=True)),
                ('asset_model', models.CharField(blank=True, max_length=32)),
                ('specification', models.CharField(blank=True, max_length=256)),
                ('asset_holder', models.CharField(blank=True, max_length=32)),
                ('asset_status', models.CharField(blank=True, max_length=32)),
                ('asset_dep', models.CharField(blank=True, max_length=32)),
                ('purchase_time', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='采购时间')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.Asset')),
            ],
            options={
                'verbose_name': '资产历史表',
                'verbose_name_plural': '资产历史表',
                'db_table': 'AssetHistory',
            },
        ),
        migrations.DeleteModel(
            name='AssetHis',
        ),
    ]
