# Generated by Django 2.2.3 on 2020-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20201224_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='asset_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
