# Generated by Django 2.2.3 on 2020-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20201224_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistory',
            name='modify_operation',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
