# Generated by Django 2.2.3 on 2020-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_assethistory_modify_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintain',
            field=models.TextField(blank=True, verbose_name='维修记录'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintain_time',
            field=models.DateTimeField(auto_now=True, verbose_name='维修日期'),
        ),
    ]
