# Generated by Django 2.2.3 on 2020-12-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20201225_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=4, null=True)),
                ('maintance_info', models.CharField(blank=True, max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '资产维修表',
                'verbose_name_plural': '资产维修表',
                'db_table': 'AssetMaintance',
            },
        ),
    ]
