# Generated by Django 2.2.3 on 2020-12-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_assetmaintance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
