# Generated by Django 2.2.3 on 2021-01-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_auto_20201228_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default=1, help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='code',
            field=models.CharField(default='', help_text='类别code', max_length=8, verbose_name='类别code'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='asset.AssetType', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='asset_type',
            field=models.CharField(max_length=16, verbose_name='资产类型名'),
        ),
    ]
