# Generated by Django 2.2.3 on 2021-01-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20210103_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetMaintance',
            new_name='AssetMaintenance',
        ),
        migrations.RenameField(
            model_name='assetmaintenance',
            old_name='maintance_info',
            new_name='maintenance_info',
        ),
        migrations.AlterModelTable(
            name='assetmaintenance',
            table='AssetMaintenance',
        ),
    ]
