# Generated by Django 2.2.3 on 2021-01-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_auto_20210103_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='maintain',
            new_name='maintenance_info',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='maintain_time',
            new_name='maintenance_time',
        ),
    ]
