# Generated by Django 2.2.3 on 2021-01-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_auto_20210104_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='maintenance_info',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maintenance_time',
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
