# Generated by Django 2.2.3 on 2021-01-05 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_auto_20210105_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacture',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商'),
        ),
        migrations.AddField(
            model_name='asset',
            name='power',
            field=models.IntegerField(blank=True, max_length=8, null=True, verbose_name='功率'),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=8, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='asset',
            name='server_type',
            field=models.CharField(blank=True, choices=[('1', '台式服务器'), ('2', '机架式服务器'), ('2', '刀片式服务器')], max_length=8, null=True, verbose_name='计算机/服务器机箱类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_model',
            field=models.CharField(blank=True, max_length=16, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.AssetStatus', verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_uuid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='唯一标示'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specification',
            field=models.CharField(blank=True, max_length=4, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='used_time',
            field=models.CharField(blank=True, default=0, max_length=8, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='asset_status',
            field=models.CharField(choices=[('1', '正常'), ('2', '损坏'), ('2', '报废')], max_length=16, verbose_name='资产状态'),
        ),
    ]
