# Generated by Django 2.2.3 on 2021-01-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_auto_20210105_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='功率'),
        ),
    ]
