# Generated by Django 2.2.3 on 2021-01-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_auto_20210105_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='power',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='功率'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='server_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='计算机/服务器机箱类型'),
        ),
    ]
