# Generated by Django 2.2.3 on 2020-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='staff_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=8, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bg_telephone',
            field=models.CharField(blank=True, max_length=16, verbose_name='办公电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=16, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='isadmin',
            field=models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='0', max_length=4, verbose_name='是否管理员'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, verbose_name='手机号码'),
        ),
    ]
