# Generated by Django 2.2.3 on 2020-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(default='', max_length=8, verbose_name='部门')),
            ],
            options={
                'verbose_name': '用户部门',
                'verbose_name_plural': '用户部门',
            },
        ),
    ]
