# Generated by Django 2.2.3 on 2020-11-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201116_2158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='User',
        ),
    ]
