# Generated by Django 2.2.3 on 2020-12-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201121_1556'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useroperatelog',
            table='UserOperateLog',
        ),
    ]
