# Generated by Django 2.2.3 on 2020-12-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201220_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroperatelog',
            name='scope',
        ),
    ]
