# Generated by Django 2.2.3 on 2020-12-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_useroperatelog_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperatelog',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetName', to='asset.Asset'),
        ),
    ]
