# Generated by Django 2.2.3 on 2020-12-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201223_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperatelog',
            name='asset_id',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='资产ID'),
        ),
    ]
